### ISSUE TITLE
Rework Custom cMap Template to move Content Tray to Accordion Items

### ISSUE THREAD

**Issue by shazahm1** [School-Apps-Today/Issue-Tracker#1]
Timesheet

- [x] Move bio field to be a jQuery UI Accordion Item. .3
- [x] Move note field (more links) to be a jQueryUI Accordion Item. .2

**Comment by jaf3778** [comment]
Text reply, I'm trying to see how this thing works. Did you get this Steve?

**Comment by shazahm1** [comment]
> Text reply, I'm trying to see how this thing works. Did you get this Steve?

yes :)

**Comment by shazahm1** [comment]
I'll get to reworking this tomorrow.

**Comment by jaf3778** [comment]
**I'll get to reworking this tomorrow.** Thanks

**Comment by shazahm1** [comment]
Are you manually quoting me in your replies? Or is that just a function with the way you are replying? I ask because there is no need to add the asterisks and repeat back to me my comment.

**Comment by jaf3778** [comment]
Are you manually quoting me in your replies?

I am surrounding your words with the double-asterisk, like I used to do in
Trello. So, are you saying that I can just bold my replies like a normal
person using Gmail tools??? No more tedious formatting of everything? :-)
Please say yes!!!

**Comment by shazahm1** [comment]
If you are replying in Gmail, just reply. The formatting in Gmail will get stripped away. The asterisks just show up as asterisk and do not bold things when replying by email.

**Comment by shazahm1** [comment]
I'm working moving the bio (tribute) to the accordion so things are going to get messy while being worked on. please do not become concerned.

**Comment by jaf3778** [comment]
Ok, thanks for letting me know

**Comment by shazahm1** [comment]
ok, both the bio and notes content trays have been moved to be accordion items:

- https://marlboroschools.schoolappstoday.com/bank/
- https://marlboroschools.schoolappstoday.com/sehs-view/
