### ISSUE TITLE
Connections Entry View

### ISSUE THREAD

**Issue by shazahm1** [School-Apps-Today/Issue-Tracker#4]
Timesheet:

- [x] First pass at adding single entry shortcode to Connections. .4
- [x] Second pass. 1
- [x] Third pass. .6

James said:

> Is there any possibility of displaying a connections users own profile (not their page) on their dashboard page (Gform post page) for them to view independent of other profiles? For example, a logged-in user would be able to preview their own profile (see screenshot to see what I mean by "profile") using an iframe perhaps? I currently use this shortcode "[user_login]" to populate the URL in a button so the current user can click on to see all their posts, like this-  /profile/[user_login]/
> 
> Here is an example that I know does not work... but maybe it will help illustrate my thinking or spark an idea? All connections users are linked to their WP user profile once registered, as you have set up previously.
> 
> Example Iframe Shortcode with-  [user_login]
> 
> [advanced_iframe use_shortcode_attributes_only="true" src="https://marlboroschools.schoolappstoday.com/connections/[user_login]/" width="100%" height="500" scrolling="yes" id="advanced_iframe" multi_domain_enabled="true" ]

![Untitled presentation (21)](https://user-images.githubusercontent.com/1185008/78940917-a3c3a080-7a84-11ea-8a27-463a2b98e92e.jpg)

**Comment by shazahm1** [comment]
Connections does not have such a feature. It gets asked for once in awhile, maybe once/twice a year so there really has not been a large community demand for such a feature so I have not taken time to add one.

Basically what would need to happen it develop a new shortcode into Connections which you could choose the entry to display, perhaps by shortcode option or by current link WP User.

**Comment by jaf3778** [comment]
**Basically what would need to happen it develop a new shortcode into
Connections which you could choose the entry to display, perhaps by
shortcode option or by current link WP User** It would be a very cool
feature for the user. How would it even be possible with a shortcode option
that is not related to "current" WP user?'

**Comment by shazahm1** [comment]
When you build things like, especially with you, you build in flexibility ... If this is something you wish to invest in, I'm think adding a new shortcode to display a single Connections Entry. The new shortcode will have one option and it will be `id` which could be set to a specific Connections Entry ID or to `current`. You know, just like with the Gravity Count where you can use WP User ID or current? So the user pattern should be something you are very familiar with.

**Comment by jaf3778** [comment]
**The new shortcode will have one option and it will be id which could be
set to a specific Connections Entry ID or to current.**

The "current" one would work well, I believe. The connections entry id
would be difficult to manage (from my viewpoint) just because that data
does not have merge tags and thing....I don't think- Either way, "Current"
would serve the purpose in this case

**Comment by shazahm1** [comment]
James said:

> I was not sure if you were going to work something up so that I could display the current users' connections profile BUT if you could whip something up I think that would add tremendous value to this project!
> 
> You see, so far, the one comment I keep getting is that the person adding a tribute does not really know where it is going.....Adding a view of their profile would help them make sense of everything better & reenforce that everything is working correctly for them.
> 
> I know you said that might be a plugin or whatever but I am just expressing how much value I think it could add to the project if you were indeed able to work some magic here at least for short term use :-) Thanks!!

**Comment by shazahm1** [comment]
Yes, this is on your approved list of things to develop.

**Comment by jaf3778** [comment]
Yes, this is on your approved list of things to develop.

I'm not sure I understand what you're saying. Is there a list on GitHub or
something that I need to look at or are you asking if we should do it?

**Comment by jaf3778** [comment]
Yes, this is on your approved list of things to develop

Okay, I think I get it, too much screentime this week,  lol. You are
working on this one because it is on the approved list, dah... Can I add
this "my tribute view" feature to the product description to be sent out
Monday morning? I think it'll bring everything together nicely, thanks!

**Comment by shazahm1** [comment]
so, I have about 1.5 hrs on this and I'm pretty sure I have something working (on my dev site, not SAT).

I had to add a new shortcode to Connections, and this is the bit which took some time. Its basically the same of the "core" `[connections]` shortcode but stripped down as much as possible to allow you to display a single entry in the correct template. That works, now I need to mod the Link addon and hook into this new shortcode to support "current" user.

**Comment by shazahm1** [comment]
oh... just remembered you're not using Link WP User to Connections Entry, you're using the GF Connector. That's going to make things a little harder than I anticipated because I will not be able to leverage the code in Link.

**Comment by jaf3778** [comment]
oh... just remembered you're not using Link WP User to Connections Entry,
you're using the GF Connector. That's going to make things a little harder
than I anticipated because I will not be able to leverage the code in Link


I am currently using a gravity form to register my users. I have found a
way to do that for this project very successfully. I'm not sure how that
factors into what you need to do but it's all good with me and, either way,
thank you!

**Comment by jaf3778** [comment]
They register here for example- /mchs-join/

Welcome page adds them to connections- graduate-thankyoupage/

Then to their dashboard.../graduate/

**Comment by jaf3778** [comment]
"I had to add a new shortcode to Connections, and this is the bit which
took some time. Its basically the same of the "core" [connections] shortcode
but stripped down as much as possible to allow you to display a single
entry in the correct template. That works, now I need to mod the Link addon
and hook into this new shortcode to support "current" user.  "

THIS IS EXCITING! I can't wait to add it to the tribute project, as it
brings everything together nicely for the new user experience!!

**Comment by shazahm1** [comment]
James said:

> I am currently using a gravity form to register my users. I have found a
> way to do that for this project very successfully. I'm not sure how that
> factors into what you need to do but it's all good with me and, either way,
> thank you!

um, yeah, that's what I said...

**Comment by jaf3778** [comment]
Gotcha

**Comment by shazahm1** [comment]
Uploaded a prototype version of Connections on SAT. Also, added a new code snippet to add "current" support to the new `[cn-entry]` shortcode. That can not be built in to Connections because "linked" entries are generally only possible with the Link addon.

Any way... please try this shortcode:

`[cn-entry id=current]`

Let me know if it works alright, share a link showing it :)

I can say it works for me on my dev site, sooo... does it break for you?

**Comment by jaf3778** [comment]
Looking good! Check it out by following below...

Login here- /login/
jbrown@sat.com
Pass-123

See current user profile here, scroll to bottom- /business/

**Comment by shazahm1** [comment]
i thought you wanted this for the tribute project

**Comment by jaf3778** [comment]
Yes, that's correct. I just put it on that business page because it's not
being used and I'm on my mobile device, so it was convenient for me to put
it there to test it out

**Comment by shazahm1** [comment]
ok, let me know after you have a chance to test it out with tributes

**Comment by jaf3778** [comment]
I did test it out with the tributes, I just put the shortcode on a
different page but it works well with the tributes!! I will share once I
work it onto the tribute dashboard :-)

**Comment by shazahm1** [comment]
k, great hear. happy this project is drawn to a close. any interest in it from any feelers you put out?

**Comment by jaf3778** [comment]
No interest yet from very limited feelers. This feature helps alot.

I need to improve some of the marketing and get a networking strategy going.
