### ISSUE TITLE
cMap Title Field

### ISSUE THREAD

**Issue by shazahm1** [School-Apps-Today/Issue-Tracker#5]
Timesheet

- [x] Adjust CSS to make Title bolder and add margin top/bottom margin to notes. .2

**Comment by shazahm1** [comment]
James said:

> Can we make the title field stand out a little more? You will see in the screenshot that it is being used for the title/ advice part of the tribute (20-word max). The notes field is being used for dedication to specific graduates. 
> 
> This way allows graduates to search the tribute page after graduation (by entering their name) to see all of the people that have dedicated a tribute to them. That should work perfectly as each school's page will contain results only from the people who have added tributes in that school category.
> 
> Does all that sound like it will function properly?

![Screenshot - 2020-04-10T083758 361](https://user-images.githubusercontent.com/1185008/79009527-a928f580-7b2d-11ea-95ef-575b3b6c41d9.png)

**Comment by shazahm1** [comment]
Ok, made it bolder and added a bit of a margin around the notes to give it a bit more whitespace.

**Comment by jaf3778** [comment]
Ok, made it bolder and added a bit of a margin around the notes to give it
a bit more whitespace

Looks great!!!
